# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  
############### start controller block ###############
  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/bionic64"
    controller.vm.hostname = 'controller'
    controller.vm.network "private_network", ip: "10.0.0.11"
    controller.vm.network "public_network"

    controller.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = "2"
      #vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  
    controller.vm.provision "shell", inline: <<-SHELL
      echo "[NECOS] git cloning necos.git"
      git clone -b rocky https://github.com/dcomp-leris/necos.git --quiet
      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
      chown -R vagrant.vagrant necos

      echo "[NECOS] apt upgrading"
      bash necos/vagrant/apt.sh

      echo "[NECOS] coping /etc/hosts"
      sudo cp necos/vagrant/hosts /etc/

      echo "[NECOS] installing chrony"
      bash necos/vagrant/chrony.sh

      echo "[NECOS] installing mariadb"
      bash necos/vagrant/mariadb.sh

      echo "[NECOS] installing rabbitmq"
      bash necos/vagrant/rabbitmq.sh

      echo "[NECOS] installing memcached"
      bash necos/vagrant/memcached.sh

      echo "[NECOS] installing etcd"
      bash necos/vagrant/etcd.sh

      echo "[NECOS] installing keystone"
      bash necos/vagrant/keystone.sh

      echo "[NECOS] installing glance"
      bash necos/vagrant/glance.sh

      echo "[NECOS] installing nova"
      bash necos/vagrant/nova.sh

      echo "[NECOS] installing neutron"
      bash necos/vagrant/neutron.sh

      echo "[NECOS] installing horizon"
      bash necos/vagrant/horizon.sh

      echo "[NECOS] installing gnocchi"
      bash necos/vagrant/gnocchi.sh

      echo "[NECOS] installing ceilometer"
      bash necos/vagrant/ceilometer.sh

      echo "[NECOS] moving log files"
      bash necos/vagrant/move.sh
    SHELL
  end
############### end controller block ###############

############### start compute1 block ###############
  config.vm.define "compute1" do |compute1|
    compute1.vm.box = "ubuntu/bionic64"
    compute1.vm.hostname = 'compute1'
    compute1.vm.network "private_network", ip: "10.0.0.31"
    compute1.vm.network "public_network"

    compute1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
      #vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  
    compute1.vm.provision "shell", inline: <<-SHELL
      echo "[NECOS] git cloning necos.git"
      git clone -b rocky https://github.com/dcomp-leris/necos.git --quiet
      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
      chown -R vagrant.vagrant necos

      echo "[NECOS] apt upgrading"
      bash necos/vagrant/apt.sh

      echo "[NECOS] coping /etc/hosts"
      sudo cp necos/vagrant/hosts /etc/

      echo "[NECOS] installing chrony"
      bash necos/vagrant/chrony-client.sh

      echo "[NECOS] installing nova"
      bash necos/vagrant/nova-compute.sh 10.0.0.31

      echo "[NECOS] installing neutron"
      bash necos/vagrant/neutron-compute.sh 10.0.0.31

      echo "[NECOS] installing ceilometer"
      bash necos/vagrant/ceilometer-compute.sh

      echo "[NECOS] moving log files"
      bash necos/vagrant/move.sh
    SHELL
  end
############### end compute1 block ###############

end
