# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.ssh.forward_x11 = true
  #swarm Node
  config.vm.define "swarm" do |swarm|
    swarm.vm.box = "ubuntu/bionic64"
    swarm.vm.hostname = 'k8s'
    swarm.vm.network "private_network", ip: "20.20.20.20"
    swarm.vm.network "public_network"
    swarm.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = "2"
    end

    swarm.vm.provision "shell", inline: <<-SHELL
      echo "[NECOS-swarm] Starting Installation :)"
      echo "[NECOS-swarm] Cloning Git..."
      git clone https://github.com/dcomp-leris/necos.git --quiet
      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
      chown -R vagrant.vagrant necos
  
      echo "[NECOS-swarm] Upgrading System..."
      bash necos/vagrantSwarm/apt.sh

      echo "[NECOS-swarm] Finishing Installation :D"
  
      echo "[NECOS-swarm] Moving Log Files."
      bash necos/vagrantSwarm/move.sh
      
    SHELL
  end
end
