# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = 'k8s'
  config.vm.network "private_network", ip: "10.0.0.11"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "[NECOS-Kubernetes] Starting Installation :)"
    echo "[NECOS-Kubernetes] git cloning necos.git"
    git clone https://github.com/dcomp-leris/necos.git --quiet
    if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
    chown -R vagrant.vagrant necos

    echo "[NECOS-Kubernetes] apt upgrading"
    bash necos/vagrantK8s/apt.sh

    echo "[NECOS-Kubernetes] moving log files"
    bash necos/vagrantK8s/move.sh
    echo "[NECOS-Kubernetes] Finishing Installation :D"
  SHELL
end
