# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

  #Master Node
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = 'k8s'
    master.vm.network "private_network", ip: "10.0.0.11"
    master.vm.network "public_network"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = "2"
    end

    master.vm.provision "shell", inline: <<-SHELL
      echo "[NECOS-Kubernetes] Starting Installation :)"
      echo "[NECOS-Kubernetes] Cloning Git..."
      git clone https://github.com/dcomp-leris/necos.git --quiet
      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
      chown -R vagrant.vagrant necos
  
      echo "[NECOS-Kubernetes] Upgrading System..."
      bash necos/vagrantK8s/apt.sh
      
      echo "[NECOS-Kubernetes] Install Docker..."
      bash necos/vagrantK8s/docker.sh   
  
      echo "[NECOS-Kubernetes] Finishing Installation :D"
  
      echo "[NECOS-Kubernetes] Moving Log Files."
      bash necos/vagrantK8s/move.sh
      
    SHELL
  end

  #Slave Node
  config.vm.define "slave" do |slave|
    slave.vm.box = "ubuntu/bionic64"
    slave.vm.hostname = 'k8s'
    slave.vm.network "private_network", ip: "10.0.0.11"
    slave.vm.network "public_network"
    slave.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = "2"
    end

    slave.vm.provision "shell", inline: <<-SHELL
      echo "[NECOS-Kubernetes] Starting Installation :)"
      echo "[NECOS-Kubernetes] Cloning Git..."
      git clone https://github.com/dcomp-leris/necos.git --quiet
      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
      chown -R vagrant.vagrant necos
  
      echo "[NECOS-Kubernetes] Upgrading System..."
      bash necos/vagrantK8s/apt.sh
      
      echo "[NECOS-Kubernetes] Install Docker..."
      bash necos/vagrantK8s/docker.sh   
  
      echo "[NECOS-Kubernetes] Finishing Installation :D"
  
      echo "[NECOS-Kubernetes] Moving Log Files."
      bash necos/vagrantK8s/move.sh    
    SHELL
  end
end
