# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.ssh.forward_x11 = true
  #minikube Node
  config.vm.define "minikube" do |minikube|
    minikube.vm.box = "ubuntu/bionic64"
    minikube.vm.hostname = 'k8s'
    minikube.vm.network "private_network", ip: "20.20.20.20"
    minikube.vm.network "public_network"
    minikube.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = "2"
    end

    minikube.vm.provision "shell", inline: <<-SHELL
      echo "[NECOS-Minikube] Starting Installation :)"
      echo "[NECOS-Minikube] Cloning Git..."
      git clone https://github.com/dcomp-leris/necos.git --quiet
      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
      chown -R vagrant.vagrant necos
  
      echo "[NECOS-Minikube] Upgrading System..."
      bash necos/vagrantK8s/apt.sh

      echo "[NECOS-Minikube] Finishing Installation :D"
  
      echo "[NECOS-Minikube] Moving Log Files."
      bash necos/vagrantK8s/move.sh
      
    SHELL
  end
end
